# Setup
title:               R0cK - Blog
tagline:             'A simple blog about cyber security.'
description:         'Blog about cyber security. CTF stuff on hackthebox and tryhackme.'
url:                 http://R0cK-blog.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Gregory Graindorge
  url:               https://www.linkedin.com/in/gr%C3%A9gory-graindorge-6b4bb96/
  email:             gregory.graindorge@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
